### ISSUE TITLE
Cell Ranger Workflow Terra:  Add path check for valid output directory prior to running workflow.

### ISSUE THREAD

**Issue by samuel-marsh** [lilab-bcb/cumulus#322]
Hi,

Currently it appears that cumulus Cell Ranger workflow on Terra executes the cell ranger functions but will then error when attempting to move results files if output path is incorrectly specified.  It would be helpful for long workflows (S4 flowcells) if there was a check prior to executing the cell ranger workflow to determine if output path was valid to stop the workflow very quickly as opposed to late error.

Thanks,
Sam

**Comment by yihming** [comment]
Hi @samuel-marsh ,

Thanks for your feedback and suggestion! We'll definitely consider it and add this check in our next release.


Sincerely,
Yiming

**Comment by yihming** [comment]
An easy-to-achieve thing is to check if `output_directory` is a valid GS URI, for example, for `gcp` backend. Is that what you are asking for?

If we want to do more, say checking if a user has write access to a Google bucket in which `output_directory` lives, that will involve more in-depth development.

**Comment by samuel-marsh** [comment]
Hi Yiming,

Thanks for quick reply!  Ya just quick check like that or if possible (I don't know enough about backend to know if it is or not) maybe make it so the output directory is similar to how you can provide `input_csv_file`.  If it's selectable then you know it's valid location.  If that's not possible then ya was just thinking quick check on the GS URI provided (for instance today copied directory path location but forgot to append gs:// on workflow and therefore it failed to copy but only after running through cell ranger steps first.

Thanks!!
Sam

**Comment by yihming** [comment]
Got it!

Unfortunately, on Terra, only `File` type workflow input can allow users select from a drop down menu. And since `output_directory` always points to a folder not file, and that folder usually is created only during the execution, it's not possible to make it choosable as nicely as `input_csv_file`.

But if just checking if it's a valid GS URI, then definitely it's impossible and easy to achieve. I'll let you know once it's available.


Sincerely,
Yiming

**Comment by yihming** [comment]
Hi @samuel-marsh ,

The output directory path checking has been added to `master` branch WDL workflows, including Cellranger. 

This feature will be in the next release of Cumulus workflows. In the meantime, you may import its `master` branch version (https://dockstore.org/workflows/github.com/lilab-bcb/cumulus/Cellranger:master) into your Terra workspace and try it on.

Thank you for providing this feedback!


Sincerely,
Yiming

**Comment by yihming** [comment]
Hi @samuel-marsh ,

Cumulus [v2.1.0](https://github.com/lilab-bcb/cumulus/releases/tag/2.1.0) is just released. Your feature request is included in this release.


Sincerely,
Yiming
