### ISSUE TITLE
Cyclic dependency error for cumulus workflow in Terra

### ISSUE THREAD

**Issue by vigneshshanmug** [lilab-bcb/cumulus#347]
Hello, 

I am able to successfully import the cumulus workflow (https://dockstore.org/workflows/github.com/lilab-bcb/cumulus/Cumulus:2.0.0?tab=versions) into terra but I am unable to load the workflow to set inputs. I am getting the following error - 

Failed to process workflow definition 'cumulus' (reason 1 of 1): This workflow contains a cyclic dependency: "Array[File] output_h5ad = cluster.output_h5ad" -> "call tasks.run_cumulus_cluster as cluster {" "call tasks.run_cumulus_cluster as cluster {" -> "Array[File] output_h5ad = cluster.output_h5ad"
 
I have attached the complete error message. 
 
Thanks so much for your help! 
 
[cumulus_error_message.docx](https://github.com/lilab-bcb/cumulus/files/9088686/cumulus_error_message.docx)

Best,
Vignesh

**Comment by yihming** [comment]
Hello Vignesh,

Thanks for reporting this issue. It has been fixed in PR #348 .


Sincerely,
Yiming
