### ISSUE TITLE
ERROR: not enough memory for BAM sorting

### ISSUE THREAD

**Issue by chadielfarran** [lilab-bcb/cumulus#371]
Hi,

I hope you are all doing well and thank you once again for creating this wonderful tool.

I am running cumulus STARsolo for 10X V3 libraries. However, I am getting the following error:

"EXITING because of fatal ERROR: not enough memory for BAM sorting: SOLUTION: re-run STAR with at least --limitBAMsortRAM 57767054690"

When I checked online, there are two solutions; one is trying with the error recommendation to add --limitBAMsortRAM to the script. Additionally, I might need to adjust the --outBAMsortingBinsN by increasing the value.

Can these functions be added to the terra cumulus starsolo workflow?

I am using the cumulus/STARsolo:master version currently.

Thank you so much for the help, and have a great rest of your day.

Best Regards,

Chadi

**Comment by yihming** [comment]
Hi @chadielfarran . Just follow up to see if your issue has been resolved. As mentioned in our email conversation, you can import https://dockstore.org/workflows/github.com/lilab-bcb/cumulus/STARsolo:starsolo?tab=versions to your Terra workspace, which has the 2 inputs you requested enabled. 

If it succeeded, I'll merge it into `master` branch for our future release.


Sincerely,
Yiming

**Comment by chadielfarran** [comment]
Hi @yihming .   The issue was resolved by adjusting  the --limitBAMsortRAM and --outBAMsortingBinsN. Thank you for adding these functions.

**Comment by yihming** [comment]
Thanks!
