### ISSUE TITLE
New version of souporcell

### ISSUE THREAD

**Issue by johnyaku** [lilab-bcb/cumulus#372]
There is a new version of `souporcell` that integrates minor changes to `troublet` in a pull request that I made.
I've made my own `souporcell` container that basically builds on yours, just over-writing the `troublet` part.
https://hub.docker.com/r/johnyaku/souporcell

But you guys seem to have your act together with the whole production container thing. So I thought I'd give you a heads up about the new version. 

I think the only line in the Dockerfile that you will need to change is this one:
https://github.com/lilab-bcb/cumulus/blob/master/docker/demultiplexing/souporcell/2021.03/Dockerfile#L46

**Comment by yihming** [comment]
@johnyaku Thanks for your info! We'll update the souporcell docker to reflect your changes.

**Comment by yihming** [comment]
The new docker image for Souporcell is created by PR #376 . The docker image is `quay.io/cumulus/souporcell:2022.12` or `cumulusprod/souporcell:2022.12` on Docker Hub. Also, it's the default souporcell version in our [demultiplexing.wdl](https://github.com/lilab-bcb/cumulus/blob/master/workflows/demultiplexing/demultiplexing.wdl#L67) workflow.
