### ISSUE TITLE
strato: command not found in Smart-Seq2 workflow

### ISSUE THREAD

**Issue by davidlieb** [lilab-bcb/cumulus#386]
Hi,

I'm running the Cumulus Smart-Seq2 workflow on Terra and am getting this error after the alignment is all done:

/cromwell_root/script: line 33: strato: command not found

Does that mean that the stratocumulus package needs to be installed in the docker file?

Thanks,

David

**Comment by yihming** [comment]
Hi @davidlieb ,

Thank you for checking it! The stratocumulus package was indeed missing in the docker image. I've rebuilt the docker, and please try the workflow again.


Sincerely,
Yiming

**Comment by davidlieb** [comment]
Thanks, Yiming! That did the trick!

David

**Comment by majorkazer** [comment]
Hello,

I am now getting the same issue when I try to run the CellRanger (v2.4.1) workflow during the mkfastq step using the default call to Broad's docker of bcl2fastq.

```
2023/10/11 21:25:03 Done localization.
2023/10/11 21:25:04 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash gcr.io/broad-cumulus/cellranger@sha256:3c9606fd60e6f61143ff652a7c2bc1b197c0e6418672ad260364811f39f73149 /cromwell_root/script
/cromwell_root/script: line 27: strato: command not found
2023/10/11 21:25:05 Starting delocalization.
```

Thanks,
Sam

**Comment by davidlieb** [comment]
Hi Sam,

Have you solved this yet? I got a different but similar error several months ago when I ran Cellranger mkfastq on Terra. I don't know if you're running on Terra, but the solution for me was to ask Terra Support to add me to the all_broad_users group. (I am affiliated with the Broad Institute and I see you are too).

David

**Comment by majorkazer** [comment]
Hi David,

Yeah, not sure why this wasn’t working. I chose to manually demultiplex
using the bcl2fastq workflow and I was able to pull the docker just fine
that way.

I’ll have to see if I run into this error the next time I try to run
cellranger mkfastq.

Thanks for checking in!

Sam
