### ISSUE TITLE
Cellranger count terra issue

### ISSUE THREAD

**Issue by Christopher-Dall** [lilab-bcb/cumulus#390]
Hi all,

Very new to terra and cellranger, so I will try to provide as much information as possible. 

I am trying to run Cellranger count on some data that I have using the terra workflow.  Using Cellranger Count V7. I have files as below

subfolder name: 23188FL-01-01-01
File names: 
     23188FL-01-01-01_S1_L007_R1_001.fastq.gz
     23188FL-01-01-01_S1_L007_R2_001.fastq.gz

My understanding, from reading cellranger count information, that the subfolder name should match the sample name, which I believe I've done as above?

I am trying to align the data to a human genome, and put the following inputs on the workflow:
TerraWorkflow_Screenshot.png

When I run the workflow, however; I get the following error:
TerraErrorCode.png

When I search the error, it seems to be a problem with the naming convention? However; I thought I named it correctly. Perhaps I misinterpreted the instructions, and need to put each fast q in a subfolder within that original folder?

Thanks so much in advance for any assistance!

Chris
<img width="1258" alt="TerraWorkflow_Screenshot" src="https://github.com/lilab-bcb/cumulus/assets/58373655/4bacca1f-9e69-49d5-ac57-70b1ef2c2f02">
<img width="1305" alt="TerraErrorCode" src="https://github.com/lilab-bcb/cumulus/assets/58373655/73fecc02-6aaa-440a-8f77-d5c60643b99f">
[workflow.6c826146-8430-4d9e-b56d-a18a23292091.log](https://github.com/lilab-bcb/cumulus/files/12928903/workflow.6c826146-8430-4d9e-b56d-a18a23292091.log)

**Comment by yihming** [comment]
Hi @Christopher-Dall ,

Thanks for reaching!

In your input, you could just state `gs://fc-0270d3cb-9d4c-4150-ae8f-cBb3b128ddfb/uploads/PDX_92723` for **output_directory**. However, even with your current input the workflow should work fine.

If possible, could you send me your job's log which contains the detailed error message? The workflow-level failure in the screenshot is just a general error message, and the log file you provided doesn't contain the error message. The log file we are looking for is `run_cellranger_count.log` in the execution folder of your job.

BTW, just FYI, `cellranger_workflow.wdl` is the top-level workflow for users to use Cell Ranger to generate gene-count matrices, while `cellranger_count.wdl` is wrapped inside it, and usually not supposed to be directly used by users.

Sincerely,
Yiming

**Comment by yihming** [comment]
I'll close this thread. Please feel free to reopen it if your issue persists.
