### ISSUE TITLE
Souporcell 2.5.0 WDL: ModuleNotFoundError: No module named 'networkx'

### ISSUE THREAD

**Issue by l-domenech-salgado** [lilab-bcb/cumulus#399]
Hi!

I'm trying to run a souporcell 2.5.0 WDL job, but I've just got this error :

Traceback (most recent call last):
  File "/opt/match_donors.py", line 210, in <module>
    matching = find_max_matching(ref_names, sample_names, mmat)
  File "/opt/match_donors.py", line 114, in find_max_matching
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'

I've checked the dockerfile and it seems we're importing networkx version 3.2.1. Could it be a version incompatibiltiy...? Could you help me with that?

(FYI: souporcell 2.4.1 WDL using the same input files works, and I see it uses networkx 2.5.1...?)

Many thanks,

Laura

**Comment by l-domenech-salgado** [comment]
Hi!

Just wanted to drop a quick update on this: I think the error occurs when attempting to run Souporcell v2.5 in Terra using the image from the Quay repository, as networkx isn't installed in that image. I noticed that the Quay repository was last updated on Oct 31, but the latest commit for the v2.5 Dockerfile on GitHub is dated Nov 17, where it appears missing dependencies are addressed.

Would it be possible to sync up the Quay repository image with the latest changes in the GitHub repository? That would be awesome!

Many thanks!!

**Comment by yihming** [comment]
Hi @l-domenech-salgado . Sorry for my late response. I'll keep you posted once this is fixed. And I'll also check if there is any other dependency missing there.

**Comment by l-domenech-salgado** [comment]
Thank you very much @yihming !

**Comment by yihming** [comment]
Hi @l-domenech-salgado . Thanks for your patience! The docker images have been rebuilt. Please check it out at your side.

**Comment by l-domenech-salgado** [comment]
Thank you very much! It worked!
