### ISSUE TITLE
Cellranger 8.0.0

### ISSUE THREAD

**Issue by xies4** [lilab-bcb/cumulus#400]
Hi, could you please build the container for Cellranger 8.0.0 when you get a chance. Thanks in advance.

**Comment by yihming** [comment]
Hi @xies4 , thank you for informing us. We'll let you know once it's done.

**Comment by yihming** [comment]
Hi @xies4 . We've just released Cumulus v2.6.0, in which Cellranger workflow uses Cell Ranger v8.0.0 by default. Please let me know if you need anything further.
