### ISSUE TITLE
CellRanger count issue in Terra workflow

### ISSUE THREAD

**Issue by Fcorrado92** [lilab-bcb/cumulus#408]
Hi all,
I am trying to run Cellranger count on a single sample using the Cellranger workflow v2.6.2 in Terra. 
I am using Cellranger V6.0.1 and reference GRCh38-2020-A.
I followed the instruction at https://cumulus.readthedocs.io/en/stable/cellranger/index.html#sample-sheet to preprare sample sheet, input and output folders.

When I run the workflow,I get the following failure message: "Job cellranger_count.run_cellranger_count:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
When I open the log file I see the following error=FileNotFoundError: [Errno 2] No such file or directory: 'strato': 'strato'
Thanks so much in advance for any assistance!

Edit: Using Cellranger V8.0.0 solved the issue in workflow v2.6.1 but I still need to use cellranger v6.0.1

Francesco

**Comment by yihming** [comment]
Hi @Fcorrado92 ,

Sorry for my late response!

I'll update the docker image for cellranger v6.0.1, and will let you know once it's ready.


Sincerely,
Yiming

**Comment by Fcorrado92** [comment]
Hi Yiming you already did! And It Is working!
Thanks you again
Francesco

Il mar 10 set 2024, 18:46 Yiming Yang ***@***.***> ha scritto:

**Comment by yihming** [comment]
Really? Maybe I did it but forgot to respond here... :-D 

I'll then close this thread. Please feel free to reach out for any future issue.
